### ISSUE TITLE
Save option for managing subscription access not working

### ISSUE THREAD

**Issue by cybers4pien** [airalab/dapp.robonomics.network#100]
**Issue:** When adding an address to manage subscription access it's not possible to save it. Save button not working.

![Screenshot from 2022-07-06 20-54-23](https://user-images.githubusercontent.com/94698086/177622850-0df734f8-33f9-4f9b-b371-2ebea5e9300a.png)

**Comment by positivecrash** [comment]
fixed in lib robonomics-ui-vue since 0.0.1-22 (will be updated in dapp soon)
