### ISSUE TITLE
Nova wallet link doesn't work

### ISSUE THREAD

**Issue by nakata5321** [airalab/dapp.robonomics.network#105]
## Problem
When I tried to install "Nova wallet" extention through our dapp, I cann't  install it with "install" button.  
![image](https://user-images.githubusercontent.com/55352168/196996581-8c682c9a-638b-4553-a2f3-3c63b81f50c4.png)

It forwards me to the wrong page. 

## Suggestion
It happens because there is wrong URL. When i copy URL to click-board,  I got this - "hhttps://novawallet.io". As you see there is extra "h" as you can see.

Please, fix it.

**Comment by positivecrash** [comment]
fixed
