### ISSUE TITLE
Staking rewards a greyed out

### ISSUE THREAD

**Issue by olivero09** [airalab/dapp.robonomics.network#111]
I use Firefox and stake some XRT, this week it seems I can not find or see my staking rewards. Can someone help? 
not here 
https://old.dapp.robonomics.network/#/staking/
or here
https://dapp.robonomics.network/#/staking/

where do I see it?
thx

**Comment by reventador855** [comment]
I am trying to newly stake. In the new dapp there doesn't seem to be a staking window. In the old dapp the bond button doesn't work. Is new staking still active? thx 
<img width="1157" alt="Screenshot 2023-01-28 at 15 41 44" src="https://user-images.githubusercontent.com/105930534/215275741-3873ee84-90cc-4976-911e-6f683a4e90e8.png">

**Comment by 0xSamsara** [comment]
Hi guys, staking is not possible anymore.

We've announced back in [November](https://robonomics.network/blog/robonomics-crowdloan-campaigns-november-2022/) staking would be discontinued after the parachain lease renewal.

And a few days ago it has been formally announced that the staking functionality has been completely phased out.

https://twitter.com/AIRA_Robonomics/status/1618227893481672704?t=FVaP8YsoeVLfA6h8OLykcw&s=19
