### ISSUE TITLE
Error processing new user addition| Key type definition error

### ISSUE THREAD

**Issue by PaTara43** [airalab/dapp.robonomics.network#117]
I have a sr25519 account
While trying to add it this account on a v0 dapp get this:
![image](https://github.com/airalab/dapp.robonomics.network/assets/34866682/6517ec6e-de23-4386-b91b-da38a1a9d76d)

Guess the WRONG SEED PHRASE error also originates from the type mismatch, still, looks wierd

Meanwhile on the new dapp I get this:
![image](https://github.com/airalab/dapp.robonomics.network/assets/34866682/4cbf3fa7-1c23-4ebb-84c6-ad6ea8f16794)

THe account is for sure in RWS. Is this a false error description for a key type as well?

**Comment by nakata5321** [comment]
Based on ussie #118 this ussie should be converted to the problem: 
 **DApp doesn't check or doesn't show that the user type account must be ED25519.**

**Comment by vol4tim** [comment]
This issue occurred because "rws setup" was not previously added to the https://dapp.robonomics.network/#/rws-setups-list list.

For such a situation, a field for entering the address of the controller has been added.

Please check if it works now?
