### ISSUE TITLE
Deleting a user from the subscription does not work correctly.

### ISSUE THREAD

**Issue by ensrationis** [airalab/dapp.robonomics.network#119]
After you click on the "delete user" button, no real transaction occurs to delete the address from the list of subscription users in Robonomics parachain

![image](https://github.com/airalab/dapp.robonomics.network/assets/14291169/f751d443-1aa3-4852-a12e-689f1f528c61)

**Comment by vol4tim** [comment]
@positivecrash Just like in issue #116, you need to add "Waiting ..." status to user delete button.
