### ISSUE TITLE
Choose IPFS gateway

### ISSUE THREAD

**Issue by nakata5321** [airalab/dapp.robonomics.network#121]
# Problem
Now in the DApp, you can choose from which IPFS gateway you want to download the datalog **only** after successfully downloading the datalog. 
So, this feature looks useless in this order. 

1) while downloading datalog:
![image](https://github.com/airalab/dapp.robonomics.network/assets/55352168/8a4dadb2-d6a5-4978-b0e7-28c7997d983f)

2)when downloaded
![image](https://github.com/airalab/dapp.robonomics.network/assets/55352168/89dd8b61-0e63-48d5-b719-35104678cc94)

# Sulution 

We should add the ability to choose a gateway while a user is trying to download a datalog.
Additionally, we need to add downloading timeout because now I've been trying to download the datalog for more than 10 minutes.

**Comment by positivecrash** [comment]
Will fix this in next release
