### ISSUE TITLE
DAO IPCI validator reward page

### ISSUE THREAD

**Issue by ensrationis** [airalab/dapp.robonomics.network#44]
Link to: https://dapp.robonomics.network/#/ipci-validator
Please fix next:
- [x] Title: DAO IPCI validators rewards by Robonomics team
- [x] Blocks: `from` `to`
- [x] Total amount of reward: 500 XRT
- [x] Validator not found

**Comment by banatarski** [comment]
How can I check `from <> to` blocks? (Starting block and end block of calculation)
Not visible in UI.
