### ISSUE TITLE
NFT card request sent. Wait for transaction on ethereum.

### ISSUE THREAD

**Issue by olivero09** [airalab/dapp.robonomics.network#48]
I filled in my polkadot account I used at the first auction and the eth address where I have my polkadot pet but nothing happens. It seems stuck.... It just says...
NFT card request sent. Wait for transaction on ethereum.

**Comment by civ-at** [comment]
facing the same issues. The transaction is pending since last Friday.
"NFT card request sent. Wait for transaction on ethereum."

**Comment by mat4711213** [comment]
same

**Comment by olivero09** [comment]
I got mine after almost 2 days of waiting. Due to ETH gas prices and high network traffic. I am sure you guys will get yours as well.

**Comment by Janemake** [comment]
Good news for you! Mine is still pending!

**Comment by vol4tim** [comment]
Hi. Transactions are periodically sent, just need to wait some time.

**Comment by dudeseb** [comment]
"NFT card request sent. Wait for transaction on ethereum"
Is that normal it takes so long time ?
