### ISSUE TITLE
Contributor NFT - No account found

### ISSUE THREAD

**Issue by onqmarketingau** [airalab/dapp.robonomics.network#49]
Hi guys. The dApp is connecting with the polkadot.js Chrome extension but only giving me one Kusama account to choose from - Will the dApp only recognise the kusama account that contributed in the first set of auctions? If not, then what needs to be done to nominate another account if it's not showing? 

If it is only recognising the accounts that contributed, then I'm stuck. I've added my eth account (connected to opensea) but nothing is happening. It still says 'no account found'.  Thanks

**Comment by SB67100** [comment]
Hi mate,

Did you find out ?

**Comment by onqmarketingau** [comment]
> Hi mate,
> 
> Did you find out ? I am experiencing same issue as your.
> 
> Cheers

No I haven't...Hoping this gets assigned.

**Comment by vol4tim** [comment]
Yes, dapp checks that address contributed KSM for Robonomics in first crowdloan.
Error "'Account not found" means this account not participated in first crowdloan.
What address you use in the dapp?

**Comment by onqmarketingau** [comment]
Thanks for getting back to me. I have three accounts in Polkadot.js but the dApp is only allowing me to choose one being DkavLwGnnjnpRrsvpQuiytmEejTyLMJKPkDqMgxmb6BFaj3. I have moved ksm around accounts, I'm actually not sure which I used to contribute in the first auction - If it wasn't that account then I can give you two others to check. If it helps I contributed 5 ksm in the first auction.

**Comment by vol4tim** [comment]
I think you need to set up a target account in the polkadot extension. For the account, you must select "Allow use on any chain."
What version of polkadot{.js} extension you use?

**Comment by onqmarketingau** [comment]
Thanks. I imported the correct account into the extension and opened the dApp and it recognised. I got to the stage of signing and submitting and then the dApp refreshed and began showing 'account not found' again for this parachain account. Can you explain what the problem is now?

**Comment by onqmarketingau** [comment]
Thanks. I had to add the second account to the Polkadot extension and allowed use on any chain. I was then able to select the right account from the dApp and have now submitted. Just waiting to receive it.

**Comment by onqmarketingau** [comment]
Hey I'm really sorry @vol4tim but I'm still waiting some 24 hours later for the nft to transfer. Do I need to have sufficient gas fees in ETH for it to transfer? Or is this delay to be expected?
