### ISSUE TITLE
NFT minting stuck at "Wait for transaction to be placed" status

### ISSUE THREAD

**Issue by alex-core-0x** [airalab/dapp.robonomics.network#54]
I have submitted minting TX ~20 hours ago.

![image](https://user-images.githubusercontent.com/4012243/132720230-e36abc98-3bb3-4e91-83ae-ebc6ac7e6426.png)

**Comment by Benny739** [comment]
same here

**Comment by Janemake** [comment]
same here! Since one week now!

**Comment by Trobriand2** [comment]
same here. Hope it will be fixed soon

**Comment by alex-core-0x** [comment]
It was probably the issue with high gas fees. Got mine minted ~3 hours ago. Issue closed.

**Comment by Cyberwave0** [comment]
I'm stuck there too. anyone knows how to solve?

**Comment by EseTeLopez** [comment]
So... what should we do?

**Comment by Janemake** [comment]
Issue closed for me too! Just received my NFT

**Comment by Cyberwave0** [comment]
Got mine too.. just matter of time.

**Comment by vol4tim** [comment]
All requested reward received.
