### ISSUE TITLE
"Stash is already bonded"

### ISSUE THREAD

**Issue by Leemo94** [airalab/dapp.robonomics.network#61]
Some users are reporting an issue that they get a "stash is already bonded" error when trying to stake multiple times.

How to recreate the issue:
Have XRT balance of for example 10 XRT, stake 2 XRT.
Then try to stake another 2 XRT, your balance is sufficient but the error message appears.

**Comment by Leemo94** [comment]
Screenshot of issue 
![image](https://user-images.githubusercontent.com/89027356/133491495-8178f7ec-792e-4cd3-a02b-b51f4572a963.png)

**Comment by vol4tim** [comment]
Presently it is impossible to use the same account for the staking.
This feature will appear when it will be implemented in https://github.com/airalab/robonomics.
