### ISSUE TITLE
Unable to redeem NFT but can verify on Subvis.io - Possibly a proxy problem

### ISSUE THREAD

**Issue by blockchainenthusiast** [airalab/dapp.robonomics.network#62]
Hello team I contributed to the first crowdloan and have been trying to claim my NFT but when check my address using the dapp my address isn't recognized as having contributed. However when I use Subvis.io or subscan to verify the contribution it shows. I also looked at the transaction via subscan and I can see the deposit made there as well. I believe the problem is the lookup tool won't recognized contributions from proxied addresses. There was no information that I saw indicating I shouldn't use a proxy to make my contribution so I was unaware that it would be a problem. Apparently it is. How can I claim and receive my nft? I don't want to post my wallet address here but I also made Samsara aware of the problem and provided the transaction details to him. I am posting the problem here because it may be a problem for other members of the community, also to hopefully improve the user experience for future rounds of crowdloans. I think there should be an ongoing alert to not contribute to the loan with a proxy or modifications made to how the app searches wallets for contributions. Perhaps checking for proxied accounts and scanning those addresses for contributions as well. Hope to hear back soon. Thank you.

**Comment by vol4tim** [comment]
Please open a new issue if you think you have a related issue.
