### ISSUE TITLE
ROBONOMICS PIONEER NFT CARD claim not working

### ISSUE THREAD

**Issue by ikhaled28** [airalab/dapp.robonomics.network#72]
- After entering the ETH address I pressed the claim button and signed the transaction. But step 3 and 4 is not shown or completed, waited more than 30 mins. Any idea for help?
- Thanks Izabul.

**Comment by Y0Y0jojo** [comment]
also  same thing continues to happen to me. I have tried for weeks now

**Comment by Y0Y0jojo** [comment]
It's not working for me on chrome
