### ISSUE TITLE
Disadvantage with my staking participation!!

### ISSUE THREAD

**Issue by Julio757** [airalab/dapp.robonomics.network#74]
Hi, I have a problem with my account, at the beginning when I blocked my XRT balance and put it to work, everything was normal.
Then I wanted to take my rewards to put them to work again, and by chance I clicked a button of "x" balance, it took 7 days for it to be unlocked and now when I want to take action again it does not allow me to do anything ... or claim nor block ..
I leave you a video so you can see what I mean, I hope you can help me, thank you very much

https://user-images.githubusercontent.com/85251988/136661846-20fef6ce-7399-41fb-9e95-837f20090ff7.mp4

**Comment by vol4tim** [comment]
This section of the dapp has been redesigned. Please check and open a new issue if you think you have a related issue.
