### ISSUE TITLE
Pioneer NFT ID claiming issues

### ISSUE THREAD

**Issue by fjp9191** [airalab/dapp.robonomics.network#76]
Hi there I tried to claim my pioneer NFT 3-4 weeks ago, and so far I have nothing in my opensea account. I have been redirected here by the telegram moderator. 

My substrate ID (KSM):  E4vVDQMz2Y95uGyNrQSn1UEge555A8aLEgoPdgJnYNnSyTr

My eth address: 0x7378a217C49b9e33c9dC063761CcAa8Cfa185650

I really hope we can resolve the issue, I have always been one of the first people to contribute to every crowdloan. Would love to have my first NFT from xrt. 
Thank you all for your hard work and continuous building.

**Comment by fjp9191** [comment]
> script

The gas price is too high everyday is what I am presuming, since I can never claim my nft. When will I be able to have my first NFT? It will not allow me to click on the claim button. Is this normal?

**Comment by vol4tim** [comment]
No requests have been received from your address. First you need to send a request to dapp https://dapp.robonomics.network/#/pioneer

If you have problems with the dapp request, please describe the problem.

**Comment by fjp9191** [comment]
> No requests have been received from your address. First you need to send a request to dapp https://dapp.robonomics.network/#/pioneer
> 
> If you have problems with the dapp request, please describe the problem.

Hey Vol4tim, the problem is that when I go to https://dapp.robonomics.network/#/pioneer and enter my kusma ID and then Ethereum ID the mouse cursor will not allow me to click on the claim button. No matter what time or day I try, I always have this issue, even if gas prices are a bit lower. Why is this the case? Shouldn't I be able to hit the claim button and then receive my XRT pioneer NFT automatically when prices are low?

![image](https://user-images.githubusercontent.com/93085575/142027068-ad95d348-1feb-424d-b8d8-0ea3a8876f2c.png)
