### ISSUE TITLE
"Stash is already bonded"

### ISSUE THREAD

**Issue by Leemo94** [airalab/dapp.robonomics.network#81]
One Robonomics user is experiencing an issue when trying to stake XRT they obtained from staking rewards.
When they try to stake this XRT, they get the error "Stash is already bonded".

Robonomics parachain address: 4ETpEm276rXU2jRiTt499W5vNmBM3Fa6HKF6so6G73XvCVTC

**Comment by vol4tim** [comment]
This section of the dapp has been redesigned. Please check and open a new issue if you think you have a related issue.
