### ISSUE TITLE
Dapp isn't recognizing crowdloan contributor addresses, so they can't claim the Pioneer NFT.

### ISSUE THREAD

**Issue by cybers4pien** [airalab/dapp.robonomics.network#83]
Community members are trying to claim their NFT and have contributed in the first or second Robonomics crowdloan campaign. 
But the addresses aren't recognized as such.

`This account was not participated in Robonomics Crowdloan 1st wave`

Secondly, change the title to:
 `This account didn't participate in first or second Robonomics Crowdloan.` as the NFT is also given to contributors in the second crowdloan.

**Comment by whinosAK** [comment]
I have contributed too and i cant claim too
