### ISSUE TITLE
XRT Balance not shown on staking page

### ISSUE THREAD

**Issue by Leemo94** [airalab/dapp.robonomics.network#85]
When trying to stake XRT, balances are not showing properly on the dapp page (https://dapp.robonomics.network/#/staking/)
See below screenshot. 

![image](https://user-images.githubusercontent.com/89027356/150163520-109a5de1-15af-4b2d-8890-6b83156907fc.png)

**Comment by vol4tim** [comment]
This issue is no relevant. Please open a new issue if you think you have a related issue.
