### ISSUE TITLE
UX Improvement when using more than 1 wallet extension

### ISSUE THREAD

**Issue by Leemo94** [airalab/dapp.robonomics.network#96]
Currently when interacting with dapp.robonomics.network with more than 1 wallet installed (for example, Polkadot JS and Talisman), the user cannot choose which wallet interacts with the dapp. It means that the user has to temporarily disable one of the extensions in their browser. 
I believe that the best way to solve this is to have a popup menu when first connecting your wallet to the dapp.

**Example from Acala's dapp:**

![1](https://user-images.githubusercontent.com/89027356/169652263-7766f284-ab7e-449e-b18c-d0004ef5f9a0.png)

**Example when connecting to dapp.robonomics.com**

![3](https://user-images.githubusercontent.com/89027356/169652286-291f3988-8e20-4a74-96a0-83876766da39.png)

**Some example repos from Talisman and Subwallet:**
1. https://github.com/TalismanSociety/talisman-connect
2. https://github.com/Koniverse/SubConnect

**Comment by positivecrash** [comment]
Done in robonomics-ui-vue lib (new dapp ui)
